version: '3.8'
services:
  server:
    image: ghcr.io/geniusyield/dex-contracts-api:latest
    container_name: server
    ports:
      - "8082:8082"
    environment:
      CORE_MAESTRO_API_KEY: ${CORE_MAESTRO_API_KEY}
      MAESTRO_API_KEY: ${MAESTRO_API_KEY}
      SERVER_API_KEY: ${SERVER_API_KEY}
      SEED_PHRASE: ${SEED_PHRASE}
      SERVER_CONFIG: |
        coreProvider:
          maestroToken: <<CORE_MAESTRO_API_KEY>>
          turboSubmit: false
        networkId: "mainnet" # supported: mainnet ot preprod
        logging:
          - type: {tag: stderr}
            severity: "Debug" # Options: Debug, Info, Warning or Error
            verbosity: V2 # Options: `V0`, `V1`, `V2`, `V3` and `V4` (See katip docs for details)
        port: 8082
        maestroToken: <<MAESTRO_API_KEY>>
        serverApiKey: <<SERVER_API_KEY>>
        wallet:
          tag: mnemonicWallet
          contents:
            mnemonic: <<SEED_PHRASE>>
    restart: always
  strategy_a:
    build:
      context: .
    environment:
      BACKEND_URL: http://server:8082
      SERVER_API_KEY: ${SERVER_API_KEY}
      EXECUTION_DELAY: 90 # Time period in seconds to wait between strategy exeuctions
      STARTUP_DELAY: 1 # Time period in seconds to wait for the backend to start
      RETRY_DELAY: 20 # Time period in seconds to wait before retrying to reach the backend
      CONFIRMATION_DELAY: 90
      STRATEGY: strategy_a
      CONFIG: |
        setting_1: 50 ADA
        setting_2: 500 ms
    depends_on:
      - server
  strategy_b:
    build:
      context: .
    environment:
      BACKEND_URL: http://server:8082
      SERVER_API_KEY: ${SERVER_API_KEY}
      EXECUTION_DELAY: 15 # Time period in seconds to wait between strategy exeuctions
      STARTUP_DELAY: 1 # Time period in seconds to wait for the backend to start
      RETRY_DELAY: 20 # Time period in seconds to wait before retrying to reach the backend
      CONFIRMATION_DELAY: 90
      STRATEGY: strategy_b
      CONFIG: |
        setting_1: 123 ADA
        setting_2: 567 ms
    depends_on:
      - server
  bollinger_bands_strategy:
    build:
      context: .
    environment:
      BACKEND_URL: http://server:8082
      SERVER_API_KEY: ${SERVER_API_KEY}
      EXECUTION_DELAY: 1 # Time period in seconds to wait between strategy exeuctions
      STARTUP_DELAY: 1 # Time period in seconds to wait for the backend to start
      RETRY_DELAY: 20 # Time period in seconds to wait before retrying to reach the backend
      CONFIRMATION_DELAY: 90
      STRATEGY: bollinger_bands_strategy
      CONFIG: |
        BASE_ASSET: lovelace
        # GENS for MAINNET:
        TARGET_ASSET: dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb.0014df1047454e53
        # tGENS for PRERPOD:
        # TARGET_ASSET: c6e65ba7878b2f8ea0ad39287d3e2fd256dc5c4160fc19bdf4c4d87e.7447454e53
        POSITION_SIZE_LOVELACES: 1000000
        STD_DEV_MULTIPLIER: 1.5
        PERIOD: 5
    depends_on:
      - server
