# coding: utf-8

"""
    GeniusYield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@geniusyield.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Market(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_asset': 'GYAssetClass',
        'market_id': 'OrderAssetPair',
        'target_asset': 'GYAssetClass'
    }

    attribute_map = {
        'base_asset': 'base_asset',
        'market_id': 'market_id',
        'target_asset': 'target_asset'
    }

    def __init__(self, base_asset=None, market_id=None, target_asset=None, _configuration=None):  # noqa: E501
        """Market - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._base_asset = None
        self._market_id = None
        self._target_asset = None
        self.discriminator = None

        self.base_asset = base_asset
        self.market_id = market_id
        self.target_asset = target_asset

    @property
    def base_asset(self):
        """Gets the base_asset of this Market.  # noqa: E501


        :return: The base_asset of this Market.  # noqa: E501
        :rtype: GYAssetClass
        """
        return self._base_asset

    @base_asset.setter
    def base_asset(self, base_asset):
        """Sets the base_asset of this Market.


        :param base_asset: The base_asset of this Market.  # noqa: E501
        :type: GYAssetClass
        """
        if self._configuration.client_side_validation and base_asset is None:
            raise ValueError("Invalid value for `base_asset`, must not be `None`")  # noqa: E501

        self._base_asset = base_asset

    @property
    def market_id(self):
        """Gets the market_id of this Market.  # noqa: E501


        :return: The market_id of this Market.  # noqa: E501
        :rtype: OrderAssetPair
        """
        return self._market_id

    @market_id.setter
    def market_id(self, market_id):
        """Sets the market_id of this Market.


        :param market_id: The market_id of this Market.  # noqa: E501
        :type: OrderAssetPair
        """
        if self._configuration.client_side_validation and market_id is None:
            raise ValueError("Invalid value for `market_id`, must not be `None`")  # noqa: E501

        self._market_id = market_id

    @property
    def target_asset(self):
        """Gets the target_asset of this Market.  # noqa: E501


        :return: The target_asset of this Market.  # noqa: E501
        :rtype: GYAssetClass
        """
        return self._target_asset

    @target_asset.setter
    def target_asset(self, target_asset):
        """Sets the target_asset of this Market.


        :param target_asset: The target_asset of this Market.  # noqa: E501
        :type: GYAssetClass
        """
        if self._configuration.client_side_validation and target_asset is None:
            raise ValueError("Invalid value for `target_asset`, must not be `None`")  # noqa: E501

        self._target_asset = target_asset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Market, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Market):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Market):
            return True

        return self.to_dict() != other.to_dict()
