# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.historical_prices_api import HistoricalPricesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoricalPricesApi(unittest.TestCase):
    """HistoricalPricesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.historical_prices_api.HistoricalPricesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v0_historical_prices_maestro_market_id_dex_get(self):
        """Test case for v0_historical_prices_maestro_market_id_dex_get

        Get price history using Maestro.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
