# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaction_api import TransactionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transaction_api.TransactionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v0_tx_sign_and_submit_post(self):
        """Test case for v0_tx_sign_and_submit_post

        Sign and submit a transaction  # noqa: E501
        """
        pass

    def test_v0_tx_sign_post(self):
        """Test case for v0_tx_sign_post

        Sign a transaction  # noqa: E501
        """
        pass

    def test_v0_tx_submit_post(self):
        """Test case for v0_tx_submit_post

        Submit a transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
