# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.assets_api import AssetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.assets_api.AssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v0_assets_asset_get(self):
        """Test case for v0_assets_asset_get

        Get assets information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
