# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.trading_fees_api import TradingFeesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTradingFeesApi(unittest.TestCase):
    """TradingFeesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.trading_fees_api.TradingFeesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v0_trading_fees_get(self):
        """Test case for v0_trading_fees_get

        Trading fees  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
