# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.orders_api.OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v0_orders_delete(self):
        """Test case for v0_orders_delete

        Cancel order(s)  # noqa: E501
        """
        pass

    def test_v0_orders_post(self):
        """Test case for v0_orders_post

        Create an order  # noqa: E501
        """
        pass

    def test_v0_orders_tx_build_cancel_post(self):
        """Test case for v0_orders_tx_build_cancel_post

        Build transaction to cancel order(s)  # noqa: E501
        """
        pass

    def test_v0_orders_tx_build_open_post(self):
        """Test case for v0_orders_tx_build_open_post

        Build transaction to create order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
