# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.gy_pub_key_hash import GYPubKeyHash  # noqa: E501
from swagger_client.rest import ApiException


class TestGYPubKeyHash(unittest.TestCase):
    """GYPubKeyHash unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGYPubKeyHash(self):
        """Test GYPubKeyHash"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.gy_pub_key_hash.GYPubKeyHash()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
