# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.asset_details import AssetDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetDetails(unittest.TestCase):
    """AssetDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetDetails(self):
        """Test AssetDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.asset_details.AssetDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
