# coding: utf-8

"""
    Genius Yield DEX Server API

    API to interact with GeniusYield DEX.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.balances_api import BalancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBalancesApi(unittest.TestCase):
    """BalancesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.balances_api.BalancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v0_balances_address_get(self):
        """Test case for v0_balances_address_get

        Balances  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
